// <auto-generated />
using EntregaModulo6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntregaModulo6.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107230527_migrationquepreste")]
    partial class migrationquepreste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntregaModulo6.Models.Pacote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("duracao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("duracao");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<float>("preco")
                        .HasMaxLength(80)
                        .HasColumnType("float")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.ToTable("pacote");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            duracao = "2 dias / 1 noite",
                            nome = "RJTRIP STANDARD",
                            preco = 2500f
                        },
                        new
                        {
                            Id = 2,
                            duracao = "3 dias / 2 noites",
                            nome = "RJTRIP PREMIUM",
                            preco = 2750f
                        },
                        new
                        {
                            Id = 3,
                            duracao = "7 dias / 6 noites",
                            nome = "RJTRIP SUPER PREMIUM",
                            preco = 4500f
                        },
                        new
                        {
                            Id = 4,
                            duracao = "2 dias / 1 noites",
                            nome = "RJTRIP IMPERIAL",
                            preco = 2900f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
